GET http://localhost:5000/signup
###

POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "username": "nopal",
    "password": "Password",
    "confirmPassword": "password"
}